[supervisord]
nodaemon=true
#loglevel = info
#logfile=/var/www/supervisord.log
#pidfile=/var/www/supervisord.pid

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /src/artisan queue:work --sleep=10 --max-time=3600
autostart=true
autorestart=true
redirect_stderr=true
stopwaitsecs=3600
