server {
    listen 443 ssl;

    server_name  localhost;

    ssl_certificate /etc/nginx/certs/localhost_cert.crt;
    ssl_certificate_key /etc/nginx/certs/localhost_cert.key;



    location /api/sgd-usuarios {
        proxy_pass http://sgd_ms_usuarios:3333;
    }

    location /api/sgd-tipodoc {
        proxy_pass http://sgd_ms_tipos_documentos:3333;
    }

    location /api/sgd-buzones {
        proxy_pass http://sgd_ms_buzones:3333;
    }


    location /api/sgd-parametros {
        proxy_pass http://sgd_ms_parametros:3333;
    }

    location /api/sgd-documentos {
        proxy_pass http://sgd_ms_documentos:3333;
    }

    location /api/sgd-archivos {
        proxy_pass http://sgd_ms_archivos:3333;
    }

    location /api/sgd-bitacora {
        proxy_pass http://sgd_ms_bitacora:3333;
    }

    location /api/sgd-buscador {
        proxy_pass http://sgd_ms_buscador:3333;
    }

    location /api/sgd-folios {
        proxy_pass http://sgd_ms_folios:3333;
    }

    location /api/sgd-firma {
        proxy_pass http://sgd_ms_firma:3333;
    }

    location /api/sgd-verifica {
        proxy_pass http://sgd_ms_verifica:3333;
    }

    location /api/sgd-notificaciones {
        proxy_pass http://sgd_ms_notificaciones:3333;
    }

    location /api/sgd-descargas {
        proxy_pass http://sgd_ms_descargas:3333;
    }

    location /api/sui {
        proxy_pass http://sgd_sui:8080;
    }

}